
version: 2

sources:
  - name: raw_bigquery_data
    database: famous-phalanx-477116-p2
    schema: healthtech_app
    loader: bigquery
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
    - name: raw_appointments
      config:
        alias: appointments
    - name: raw_patients
      config:
        alias: patients
    - name: raw_slots
      config:
        alias: slots
