
version: 2

sources:
  - name: raw_bigquery_data
    database: famous-phalanx-477116-p2
    schema: healthtech_app
    loader: bigquery
    config:
      freshness:
        warn_after: {count: 12, period: hour}
    tables:
      - name: appointments
        identifier: raw_appointments
        description: appointment scheduling information between 2014 and 2024 with appointment_id as unique identifier
        config:
          loaded_at_field: scheduling_date
        columns:
          - name: appointment_id
            description: unique identifier for each appointment
            tests:
              - unique
              - not_null
          - name: slot_id
            description: refers to the slot in the slots table
            tests:
              - not_null
          - name: scheduling_date
            description: date for when the appointment was scheduled
            tests:
              - not_null
          - name: appointment_date
            description: date of the appointment
            tests:
              - not_null
          - name: appointment_time
            description: scheduled time of the appointment
            tests:
              - not_null
          - name: scheduling_interval
            description: days between scheduling and appointment date
            tests:
              - not_null
          - name: status
            description: appointment status
            data_tests:
              - accepted_values:
                  values: ['unknown', 'scheduled', 'attended', 'cancelled', 'did not attend']
          - name: check_in_time
            description: actual time the patient checked in
          - name: appointment_duration
            description: duration of the appointment in minutes
          - name: start_time
            description: actual start time of the appointment
          - name: end_time
            description: actual end time of the appointment
          - name: waiting_time
            description: waiting time in minutes
          - name: patient_id
            description: refers to the patient in the patients table
            tests:
              - not_null
          - name: sex
            description: gender of the patient
            tests:
              - not_null
          - name: age
            description: age of the patient
            tests:
              - not_null
          - name: age_group
            description: age group category of the patient
            tests:
              - not_null
      - name: patients
        identifier: raw_patients
        description: patient information with patient_id as the unique identifier
        config:
          loaded_at_field: patient_id
        columns:
          - name: patient_id
            description: unique identifier for each patient
            tests:
              - unique
              - not_null
          - name: name
            description: full name of patient 
            tests:
              - not_null
          - name: sex
            description: gender of patient (male, female, non-binary)
            data_tests:
              - accepted_values:
                  values: ['Male', 'Female', 'Non-Binary']
          - name: dob
            description: date of birth of patient in yyyy-mm-dd
            tests:
              - not_null   
          - name: insurance
            description: name of the patient's insurance provider from a predefined list of fictitious names
            tests:
              - not_null            
      - name: slots
        identifier: raw_slots
        description: information about time slots available/not available for appointments with slot_id as the unique identifier
        config:
          loaded_at_field: appointment_date
        columns:
          - name: slot_id
            description: unique identifier for each time slot
            tests:
              - unique
              - not_null
          - name: appointment_date
            description: date of the appointment
            tests:
              - not_null
          - name: appointment_time
            description: scheduled time of the appointment (15 min intervals)
            tests:
              - not_null
          - name: is_available
            description: boolean indicating if the slot if available or not
            tests:
              - not_null            